/**
* Schachfish-Api
* Schachfish is a chess engine for querying moves and board evaluations
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.nicholasbrooking.pkg.schachfish.api.models

import com.nicholasbrooking.pkg.schachfish.api.models.PieceDto

import com.squareup.moshi.Json
/**
 * 
 * @param canCastleKingSide 
 * @param canCastleQueenSide 
 * @param pieces 
 */

data class ColourStatusDto (
    @Json(name = "canCastleKingSide")
    val canCastleKingSide: kotlin.Boolean? = null,
    @Json(name = "canCastleQueenSide")
    val canCastleQueenSide: kotlin.Boolean? = null,
    @Json(name = "pieces")
    val pieces: kotlin.Array<PieceDto>? = null
)

