/**
* Schachfish-Api
* Schachfish is a chess engine for querying moves and board evaluations
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.nicholasbrooking.pkg.schachfish.api.models

import com.nicholasbrooking.pkg.schachfish.api.models.MoveDto

import com.squareup.moshi.Json
/**
 * 
 * @param moves 
 */

data class MoveCollectionDto (
    @Json(name = "moves")
    val moves: kotlin.Array<MoveDto>? = null
)

