/**
* Schachfish-Api
* Schachfish is a chess engine for making/querying moves and board evaluations
*
* The version of the OpenAPI document: 1.0.0
* 
*
* NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
* https://openapi-generator.tech
* Do not edit the class manually.
*/
package com.nicholasbrooking.pkg.schachfish.api.models


import com.squareup.moshi.Json

/**
* 
* Values: king,queen,rook,bishop,knight,pawn
*/

enum class PieceName(val value: kotlin.String){


    @Json(name = "king")
    king("king"),


    @Json(name = "queen")
    queen("queen"),


    @Json(name = "rook")
    rook("rook"),


    @Json(name = "bishop")
    bishop("bishop"),


    @Json(name = "knight")
    knight("knight"),


    @Json(name = "pawn")
    pawn("pawn");



	/**
	This override toString avoids using the enum var name and uses the actual api value instead.
	In cases the var name and value are different, the client would send incorrect enums to the server.
	**/
	override fun toString(): String {
        return value
    }

}

